version: '3.7'
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

  redis:
    image: redis:latest
    ports:
      - 6379:6379
 
volumes:
  mongodb: