apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rabbit
  name: rabbit
spec:
  externalName: rabbit
  selector:
    app: rabbit
  type: ExternalName
status:
  loadBalancer: {}
